### ISSUE TITLE
 Helium Theme:  the class="justified-gallery" is not there anymore.

### ISSUE THREAD

**Issue by beamaria** [sal0max/grav-plugin-shortcode-gallery-plusplus#24]
@sal0max Hi I have the same problem with Helium:  the class="justified-gallery" is not there anymore.

My settings:
Shortcode gallery+++ v 1.2.1
Helium v 5.5.11
Gantry 5 v 5.5.11
Grav v.1.7.30
Admin Panel v. 1.10.30.2

I tried to locate the base.html.twig file of the theme, but i couldn't find it

Any idea how to fix the issue?

_Originally posted by @beamaria in https://github.com/sal0max/grav-plugin-shortcode-gallery-plusplus/issues/22#issuecomment-1047846191_

**Comment by beamaria** [comment]
Any news about this issue??

**Comment by sal0max** [comment]
Like already said in the other issue: Such behavior is likely due to other faulty plugins or themes.
If you really want to have this fixed, you need to first isolate the problem.

I took the time to create a new Grav instance like in your description, and it works flawlessly, like you can see in attached screenshot.
Must be another plugin. 

![gantry_helium](https://user-images.githubusercontent.com/423373/157567674-07af4ba2-554e-46fc-9946-558f2eb49fb4.png)

**Comment by beamaria** [comment]
Hi, I'm sorry for my stupidity... I forgot to enable the captions in the general settings of the plugin 🙃
I closed the issue.
Thanks for taking the time to check it

Eilis

**Comment by beamaria** [comment]
Hi, I'm sorry for my stupidity... I forgot to enable the captions in the general settings of the plugin 🙃
I closed the issue.
Thanks for taking the time to check it
