### ISSUE TITLE
Gantry 5 Adding Shortcode in Custom HTML Particle Fails

### ISSUE THREAD

**Issue by EthicalObligation** [sal0max/grav-plugin-shortcode-gallery-plusplus#29]
![image](https://user-images.githubusercontent.com/92163467/180480239-64a8a48f-9db4-4542-a51c-290976ed1c54.png)
![image](https://user-images.githubusercontent.com/92163467/180480268-356a19a8-4cf5-4620-b29c-08549236e047.png)

**Comment by sal0max** [comment]
Gantry is a project I'm not familiar with, and a project I don't plan on getting familiar with anytime soon.

As the problem seems to only appear there and not when this plugin is regularly used, I'd say this is something Gantry has to fix. As long as you can't point out what could cause the problem that is this plugins responsibility, I won't look into this.

**Comment by Sailoriae** [comment]
Hello,
I think it's because the Gantry plugin doesn't trigger event the same way Grav does for a normal display of the page.
The solution would be to check if `$currentPage` isn't `null` before using. I can do a PR if you wish, that was my code. ^^
In the meantime, have a nice day/evening !

**Comment by EthicalObligation** [comment]
> Hello, I think it's because the Gantry plugin doesn't trigger event the same way Grav does for a normal display of the page. The solution would be to check if `$currentPage` isn't `null` before using. I can do a PR if you wish, that was my code. ^^ In the meantime, have a nice day/evening !

That would be greatly appreciated!

**Comment by Sailoriae** [comment]
(I'm sorry for the wait time, but I'm waiting for @sal0max to answer to my PR #32)
